In [24]:
import numpy as np

sales_1d = np.array([100, 120, 110])
sales_1d

array([100, 120, 110])

In [25]:
sales_head = sales_1d[0]
sales_head

np.int64(100)

In [26]:
sales_tail = sales_1d[-1]
sales_tail

np.int64(110)

In [27]:
sales_after_1 = sales_1d[1:3]
sales_after_1

array([120, 110])

In [28]:
sales_0_2 = sales_1d[[0, 2]]
sales_0_2

array([100, 110])

In [29]:
sales_2d = np.array([[100, 120, 110],
                     [150, 140, 130]])
sales_2d

array([[100, 120, 110],
       [150, 140, 130]])

In [30]:
sales_row = sales_2d[0]
sales_row

array([100, 120, 110])

In [31]:
sales_shop1_day2 = sales_2d[0, 1]
sales_shop1_day2

np.int64(120)

In [32]:
sales_col = sales_2d[:, 1]
sales_col

array([120, 140])

In [33]:
sales_all_after_day2 = sales_2d[:, 1:]
sales_all_after_day2

array([[120, 110],
       [140, 130]])

In [34]:
sales_all_0_2 = sales_2d[:, [0, 2]]
sales_all_0_2

array([[100, 110],
       [150, 130]])

In [35]:
import numpy as np

data = np.array([10, 20, 30, 40])

In [36]:
data[0]

np.int64(10)

In [37]:
data[-1]

np.int64(40)

In [38]:
data[1:]

array([20, 30, 40])

In [39]:
data[[0, 2]]

array([10, 30])

In [40]:
scores = np.array(
    [[70, 80, 90],
     [60, 75, 85],
     [95, 88, 92]]
)

In [41]:
scores[0]

array([70, 80, 90])

In [42]:
scores[1, 1]

np.int64(75)

In [43]:
scores[:, 1]

array([80, 75, 88])

In [47]:
scores[:, [0, 2]]

array([[70, 90],
       [60, 85],
       [95, 92]])