In [4]:
import numpy as np

temps = np.array([20, 22, 25, 28, 27,30, 24])
temps

array([20, 22, 25, 28, 27, 30, 24])

In [5]:
mean_temp = temps.mean()

In [6]:
mean_temp

np.float64(25.142857142857142)

In [8]:
max_temp = temps.max()
max_temp

np.int64(30)

In [9]:
diff_temps = np.diff(temps)
diff_temps

array([ 2,  3,  3, -1,  3, -6])

In [10]:
sales = np.array([100, 120, 90, 150, 130])

In [12]:
mean_sales = sales.mean()
mean_sales

np.float64(118.0)

In [13]:
max_sales = sales.max()
max_sales

np.int64(150)

In [14]:
diff_sales = np.diff(sales)
diff_sales

array([ 20, -30,  60, -20])

In [15]:
import numpy as np

defects = np.array([5, 7, 4, 4, 9, 6])

mean_defects = defects.mean()
max_defects = defects.max()
diff_defects = np.diff(defects)
sum_defects = defects.sum()

mean_defects, max_defects, diff_defects, sum_defects

(np.float64(5.833333333333333),
 np.int64(9),
 array([ 2, -3,  0,  5, -3]),
 np.int64(35))