# 134-5 NumPyの便利な機能

## 1問目 統計値・要素間の差分


In [4]:
import numpy as np

temps = np.array([20, 22, 25, 28, 27,30, 24])
temps

array([20, 22, 25, 28, 27, 30, 24])

In [5]:
mean_temp = temps.mean()

In [6]:
mean_temp

np.float64(25.142857142857142)

In [8]:
max_temp = temps.max()
max_temp

np.int64(30)

In [9]:
diff_temps = np.diff(temps)
diff_temps

array([ 2,  3,  3, -1,  3, -6])

In [10]:
sales = np.array([100, 120, 90, 150, 130])

In [12]:
mean_sales = sales.mean()
mean_sales

np.float64(118.0)

In [13]:
max_sales = sales.max()
max_sales

np.int64(150)

In [14]:
diff_sales = np.diff(sales)
diff_sales

array([ 20, -30,  60, -20])

In [15]:
import numpy as np

defects = np.array([5, 7, 4, 4, 9, 6])

mean_defects = defects.mean()
max_defects = defects.max()
diff_defects = np.diff(defects)
sum_defects = defects.sum()

mean_defects, max_defects, diff_defects, sum_defects

(np.float64(5.833333333333333),
 np.int64(9),
 array([ 2, -3,  0,  5, -3]),
 np.int64(35))

# 134-5 NumPyの便利な機能

## 2問目 ユニバーサルファンクション

In [16]:
import numpy as np

temps = np.array([20, 22, 25, 28, 27, 30, 24])
temps

array([20, 22, 25, 28, 27, 30, 24])

In [17]:
diff_temps = np.diff(temps)
diff_temps

array([ 2,  3,  3, -1,  3, -6])

In [18]:
abs_diff_temps = np.abs(diff_temps)
abs_diff_temps

array([2, 3, 3, 1, 3, 6])

In [19]:
np.abs(diff_temps)

array([2, 3, 3, 1, 3, 6])

In [20]:
result = []

for x in diff_temps:
    result.append(abs(x))

In [21]:
result

[np.int64(2), np.int64(3), np.int64(3), np.int64(1), np.int64(3), np.int64(6)]

In [22]:
np.abs(diff_temps)

array([2, 3, 3, 1, 3, 6])

In [23]:
import numpy as np

changes = np.array([5, -3, 8, -10, 0])

abs_changes = np.abs(changes)
abs_changes

array([ 5,  3,  8, 10,  0])

In [24]:
import numpy as np

defect_changes = np.array([2, -1, 0, 5, -3])
abs_defect_changes = np.abs(defect_changes)
abs_defect_changes

array([2, 1, 0, 5, 3])

# 134-5 NumPyの便利な機能

## 3問目 形状の変換

In [25]:
import numpy as np

temps = np.array([20, 22, 25, 28, 27, 30, 24, 25, 26, 32, 31, 30, 29, 25])
temps

array([20, 22, 25, 28, 27, 30, 24, 25, 26, 32, 31, 30, 29, 25])

In [26]:
temps.shape

(14,)

In [28]:
temps_week = temps.reshape(2, 7)
temps_week

array([[20, 22, 25, 28, 27, 30, 24],
       [25, 26, 32, 31, 30, 29, 25]])

In [29]:
temps_week.shape

(2, 7)

In [31]:
temps_1d = temps_week.flatten()
temps_1d

array([20, 22, 25, 28, 27, 30, 24, 25, 26, 32, 31, 30, 29, 25])

In [34]:
import numpy as np

sales = np.array([100, 120, 110, 130, 150, 140, 160, 170, 180, 190, 200, 210])

sales_2d = sales.reshape((3, 4))
sales_2d

array([[100, 120, 110, 130],
       [150, 140, 160, 170],
       [180, 190, 200, 210]])

In [35]:
sales_1d = sales_2d.flatten()

In [36]:
sales_1d

array([100, 120, 110, 130, 150, 140, 160, 170, 180, 190, 200, 210])