In [1]:
import numpy as np

prices = np.array(
    [[100, 130, 180],
     [110, 135, 190]])
prices

array([[100, 130, 180],
       [110, 135, 190]])

In [2]:
prices.shape

(2, 3)

In [3]:
discounts_1d = np.array([10, 20, 25])
discounts_1d

array([10, 20, 25])

In [5]:
discounts_1d.shape

(3,)

In [6]:
print(prices.shape)
print(discounts_1d.shape)

(2, 3)
(3,)


In [7]:
discounted_prices = prices - discounts_1d
discounted_prices

array([[ 90, 110, 155],
       [100, 115, 165]])

In [8]:
discounts_2d = np.array(
    [[10, 20, 25],
     [10, 20, 25]]
)
prices - discounts_2d

array([[ 90, 110, 155],
       [100, 115, 165]])

In [9]:
import numpy as np

prices2 = np.array(
    [[200, 300, 400],
     [250, 350, 450]]
)
prices2

array([[200, 300, 400],
       [250, 350, 450]])

In [10]:
discounts2_1d = np.array([20, 30, 40])
discounts2_1d

array([20, 30, 40])

In [11]:
discounted_prices = prices2 - discounts2_1d
discounted_prices

array([[180, 270, 360],
       [230, 320, 410]])

In [12]:
shipping_fees = np.array([5, 10, 15])
shipping_fees

array([ 5, 10, 15])

In [15]:
prices_with_shipping = prices + shipping_fees

In [16]:
prices_with_shipping

array([[105, 140, 195],
       [115, 145, 205]])