In [1]:
import numpy as np

prices = np.array(
    [[100, 130, 180],
     [110, 135, 190]])
prices

array([[100, 130, 180],
       [110, 135, 190]])

In [2]:
prices.shape

(2, 3)

In [3]:
prices_with_tax = prices * 1.08
prices_with_tax

array([[108. , 140.4, 194.4],
       [118.8, 145.8, 205.2]])

In [4]:
import numpy as np

prices2 = np.array(
    [[200, 300],
     [250, 350]])
prices2

array([[200, 300],
       [250, 350]])

In [5]:
prices2.shape

(2, 2)

In [6]:
prices2_with_tax = prices2 * 1.08
prices2_with_tax

array([[216., 324.],
       [270., 378.]])

In [7]:
prices_with_tax_10 = prices * 1.10
prices_with_tax_10

array([[110. , 143. , 198. ],
       [121. , 148.5, 209. ]])