In [1]:
import numpy as np

prices = np.array([[100, 130, 180],
                   [110, 135, 190]])

quantities = np.array([20, 10, 5])

print(prices.shape)
print(quantities.shape)

(2, 3)
(3,)


In [2]:
total_prices = prices @ quantities

In [3]:
total_prices

array([4200, 4500])

In [4]:
total_prices = np.dot(prices, quantities)
total_prices

array([4200, 4500])

In [5]:
import numpy as np

prices2 = np.array([[200, 300, 400],
                    [250, 350, 450]])
prices2

array([[200, 300, 400],
       [250, 350, 450]])

In [6]:
quantities2 = np.array([2, 3, 4])

In [7]:
quantities2

array([2, 3, 4])

In [8]:
total_prices2 = prices2 @ quantities2
total_prices2

array([2900, 3350])

In [9]:
amounts = prices * quantities

In [10]:
amounts

array([[2000, 1300,  900],
       [2200, 1350,  950]])

In [11]:
total_prices_from_amounts = amounts.sum(axis=1)

In [12]:
total_prices_from_amounts

array([4200, 4500])

In [13]:
amounts = prices * quantities

In [14]:
amounts

array([[2000, 1300,  900],
       [2200, 1350,  950]])

In [15]:
total_prices_from_amounts = amounts.sum(axis=1)

In [16]:
amounts = prices * quantities
amounts

array([[2000, 1300,  900],
       [2200, 1350,  950]])