In [1]:
import numpy as np

prices = np.array(
    [[100, 130, 180],
     [110, 135, 190]]
)
prices

array([[100, 130, 180],
       [110, 135, 190]])

In [2]:
discounts = np.array(
    [[10, 20, 25],
     [5, 8, 10]]
)
discounts

array([[10, 20, 25],
       [ 5,  8, 10]])

In [3]:
print(prices.shape)

(2, 3)


In [4]:
print(discounts.shape)

(2, 3)


In [5]:
prices.shape

(2, 3)

In [6]:
discounts.shape

(2, 3)

In [7]:
discounted_prices = prices - discounts
discounted_prices

array([[ 90, 110, 155],
       [105, 127, 180]])

In [8]:
prices - discounts

array([[ 90, 110, 155],
       [105, 127, 180]])

In [9]:
import numpy as np

prices2 = np.array(
    [[200, 300],
     [250, 350]]
)
prices2

array([[200, 300],
       [250, 350]])

In [10]:
discounts2 = np.array(
    [[20, 30],
     [10, 50]]
)
discounts2

array([[20, 30],
       [10, 50]])

In [11]:
discounted_prices2 = prices2 - discounts2
discounted_prices2

array([[180, 270],
       [240, 300]])

In [12]:
increses = np.array(
    [[5, 10, 15],
     [10, 15, 20]]
)
raised_prices = prices + increses
raised_prices

array([[105, 140, 195],
       [120, 150, 210]])