## 「135-1: NumPy配列（ndarray）の基本」 1問目

In [1]:
import numpy as np

In [2]:
scores_list_1d = [62, 90, 75, 98, 88]
scores_1d = np.array(scores_list_1d)
scores_1d

array([62, 90, 75, 98, 88])

In [3]:
type(scores_1d)

numpy.ndarray

In [4]:
scores_1d.shape

(5,)

In [5]:
scores_list_2d = [
    [62, 90, 75, 98, 88],
    [79, 78, 81, 82, 76],
    [91, 83, 90, 65, 71],
]

scores_2d = np.array(scores_list_2d)
scores_2d

array([[62, 90, 75, 98, 88],
       [79, 78, 81, 82, 76],
       [91, 83, 90, 65, 71]])

In [6]:
scores_2d.shape

(3, 5)

In [7]:
scores_list_3d = [
    [
        [62, 90, 75, 98, 88],
        [79, 78, 81, 82, 76],
        [91, 83, 90, 65, 71],
    ],
    [
        [73, 89, 82, 91, 83],
        [89, 85, 98, 96, 72],
        [98, 85, 92, 70, 81],
    ],
]

scores_3d = np.array(scores_list_3d)
scores_3d

array([[[62, 90, 75, 98, 88],
        [79, 78, 81, 82, 76],
        [91, 83, 90, 65, 71]],

       [[73, 89, 82, 91, 83],
        [89, 85, 98, 96, 72],
        [98, 85, 92, 70, 81]]])

In [8]:
scores_3d.shape

(2, 3, 5)

In [10]:
import numpy as np

prices_list = [100, 200, 300]

prices = np.array(prices_list)
prices

array([100, 200, 300])

In [11]:
prices.shape

(3,)

In [12]:
import numpy as np

scores_list = [
    [80, 70, 90],
    [60, 75, 85],
]

scores = np.array(scores_list)
scores

array([[80, 70, 90],
       [60, 75, 85]])

In [13]:
scores.shape

(2, 3)

In [16]:
import numpy as np

scores_list_2d = [
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 79],
    [55, 68, 72],
]

scores_2d = np.array(scores_list_2d)
scores_2d

array([[70, 80, 90],
       [60, 75, 85],
       [88, 92, 79],
       [55, 68, 72]])

In [17]:
scores_2d.shape

(4, 3)