## 「136-1: NumPデータの連結・分割」 1問目

In [2]:
import numpy as np

rainfalls_ab = np.array([[120, 130, 140],
                        [115, 140, 135]])

rainfalls_cd = np.array([[130, 125, 140],
                        [90, 120, 100]])

rainfalls_ab_2 = np.array([[90, 100, 115],
                          [120, 95, 105]])

In [3]:
rainfalls_ab_cd = np.vstack([rainfalls_ab, rainfalls_cd])
rainfalls_ab_cd

array([[120, 130, 140],
       [115, 140, 135],
       [130, 125, 140],
       [ 90, 120, 100]])

In [4]:
rainfalls_ab_all = np.hstack([rainfalls_ab, rainfalls_ab_2])
rainfalls_ab_all

array([[120, 130, 140,  90, 100, 115],
       [115, 140, 135, 120,  95, 105]])

In [5]:
np.concatenate([rainfalls_ab, rainfalls_cd], axis=0)

array([[120, 130, 140],
       [115, 140, 135],
       [130, 125, 140],
       [ 90, 120, 100]])

In [6]:
np.concatenate([rainfalls_ab, rainfalls_ab_2], axis=1)

array([[120, 130, 140,  90, 100, 115],
       [115, 140, 135, 120,  95, 105]])

In [8]:
import numpy as np

data_1 = np.array([[1, 2],
                   [3, 4]])

data_2 = np.array([[5, 6],
                   [7, 8]])

data_v = np.vstack([data_1, data_2])
data_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
import numpy as np
data_1 = np.array([[1, 2],
                   [3, 4]])

data_3 = np.array([[10, 20],
                   [30, 40]])

data_h = np.hstack([data_1, data_3])
data_h

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

In [10]:
data_v2 = np.concatenate([data_1, data_2], axis=0)

In [11]:
data_v2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
data_h2 = np.concatenate([data_1, data_3], axis=1)
data_h2

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

## 136-1: NumPデータの連結・分割

In [13]:
import numpy as np

rainfalls_all = np.array(
    [
        [120, 130, 140, 110, 90, 100, 115, 135, 145, 110, 105, 125],
        [115, 140, 135, 120, 95, 105, 110, 120, 150, 115, 110, 130],
        [130, 125, 140, 115, 100, 90, 120, 125, 155, 130, 115, 140],
    ]
)

rainfalls_all

array([[120, 130, 140, 110,  90, 100, 115, 135, 145, 110, 105, 125],
       [115, 140, 135, 120,  95, 105, 110, 120, 150, 115, 110, 130],
       [130, 125, 140, 115, 100,  90, 120, 125, 155, 130, 115, 140]])

In [14]:
rainfalls_all.shape

(3, 12)

In [15]:
data_q = np.hsplit(rainfalls_all, 4)
data_q

[array([[120, 130, 140],
        [115, 140, 135],
        [130, 125, 140]]),
 array([[110,  90, 100],
        [120,  95, 105],
        [115, 100,  90]]),
 array([[115, 135, 145],
        [110, 120, 150],
        [120, 125, 155]]),
 array([[110, 105, 125],
        [115, 110, 130],
        [130, 115, 140]])]

In [16]:
data_q[0]

array([[120, 130, 140],
       [115, 140, 135],
       [130, 125, 140]])

In [17]:
np.hsplit(rainfalls_all, [3, 6, 9])

[array([[120, 130, 140],
        [115, 140, 135],
        [130, 125, 140]]),
 array([[110,  90, 100],
        [120,  95, 105],
        [115, 100,  90]]),
 array([[115, 135, 145],
        [110, 120, 150],
        [120, 125, 155]]),
 array([[110, 105, 125],
        [115, 110, 130],
        [130, 115, 140]])]

In [18]:
data_a_bc = np.vsplit(rainfalls_all, [1])
data_a_bc

[array([[120, 130, 140, 110,  90, 100, 115, 135, 145, 110, 105, 125]]),
 array([[115, 140, 135, 120,  95, 105, 110, 120, 150, 115, 110, 130],
        [130, 125, 140, 115, 100,  90, 120, 125, 155, 130, 115, 140]])]

In [20]:
print("都市Aのデータ")
print(data_a_bc[0])

print("都市B,Cのデータ")
print(data_a_bc[1])

都市Aのデータ
[[120 130 140 110  90 100 115 135 145 110 105 125]]
都市B,Cのデータ
[[115 140 135 120  95 105 110 120 150 115 110 130]
 [130 125 140 115 100  90 120 125 155 130 115 140]]


In [22]:
import numpy as np

data = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

data_lr = np.hsplit(data, 2)
data_lr


[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [23]:
import numpy as np

data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

data_ud = np.vsplit(data, 2)
data_ud


[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [24]:
import numpy as np

data = np.array([
    [10, 20, 30, 40, 50],
    [60, 70, 80, 90, 100]
])

data_split_col = np.hsplit(data, [2])
data_split_col

[array([[10, 20],
        [60, 70]]),
 array([[ 30,  40,  50],
        [ 80,  90, 100]])]

In [26]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

data_split_row = np.vsplit(data, [1])
data_split_row

[array([[10, 20, 30]]),
 array([[40, 50, 60],
        [70, 80, 90]])]

## 136-1の総復習問題

In [27]:
import numpy as np

scores_1 = np.array([[75, 82, 72, 61, 68, 90],
                     [85, 78, 100, 95, 92, 88]])

scores_2 = np.array([[80, 74, 82, 91, 89, 85],
                     [70, 81, 89, 83, 75, 87]])

In [28]:
scores_1.shape

(2, 6)

In [29]:
scores_2.shape

(2, 6)

In [30]:
scores_all = np.vstack([scores_1, scores_2])
scores_all

array([[ 75,  82,  72,  61,  68,  90],
       [ 85,  78, 100,  95,  92,  88],
       [ 80,  74,  82,  91,  89,  85],
       [ 70,  81,  89,  83,  75,  87]])

In [31]:
pre, post = np.hsplit(scores_all, 2)

In [32]:
pre

array([[ 75,  82,  72],
       [ 85,  78, 100],
       [ 80,  74,  82],
       [ 70,  81,  89]])

In [33]:
post

array([[61, 68, 90],
       [95, 92, 88],
       [91, 89, 85],
       [83, 75, 87]])

In [35]:
scores_all = np.concatenate([scores_1, scores_2], axis=0)

In [36]:
import numpy as np

data_1 = np.array([[10, 20, 30],
                   [40, 50, 60]])

data_2 = np.array([[70, 80, 90],
                   [100, 110, 120]])

data_all = np.vstack([data_1, data_2])
data_all

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [37]:
first, second = np.hsplit(data_all, [2])

In [38]:
first

array([[ 10,  20],
       [ 40,  50],
       [ 70,  80],
       [100, 110]])

In [39]:
second

array([[ 30],
       [ 60],
       [ 90],
       [120]])