## 「136-1: NumPデータの連結・分割」 1問目

In [2]:
import numpy as np

rainfalls_ab = np.array([[120, 130, 140],
                        [115, 140, 135]])

rainfalls_cd = np.array([[130, 125, 140],
                        [90, 120, 100]])

rainfalls_ab_2 = np.array([[90, 100, 115],
                          [120, 95, 105]])

In [3]:
rainfalls_ab_cd = np.vstack([rainfalls_ab, rainfalls_cd])
rainfalls_ab_cd

array([[120, 130, 140],
       [115, 140, 135],
       [130, 125, 140],
       [ 90, 120, 100]])

In [4]:
rainfalls_ab_all = np.hstack([rainfalls_ab, rainfalls_ab_2])
rainfalls_ab_all

array([[120, 130, 140,  90, 100, 115],
       [115, 140, 135, 120,  95, 105]])

In [5]:
np.concatenate([rainfalls_ab, rainfalls_cd], axis=0)

array([[120, 130, 140],
       [115, 140, 135],
       [130, 125, 140],
       [ 90, 120, 100]])

In [6]:
np.concatenate([rainfalls_ab, rainfalls_ab_2], axis=1)

array([[120, 130, 140,  90, 100, 115],
       [115, 140, 135, 120,  95, 105]])

In [8]:
import numpy as np

data_1 = np.array([[1, 2],
                   [3, 4]])

data_2 = np.array([[5, 6],
                   [7, 8]])

data_v = np.vstack([data_1, data_2])
data_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
import numpy as np
data_1 = np.array([[1, 2],
                   [3, 4]])

data_3 = np.array([[10, 20],
                   [30, 40]])

data_h = np.hstack([data_1, data_3])
data_h

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

In [10]:
data_v2 = np.concatenate([data_1, data_2], axis=0)

In [11]:
data_v2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
data_h2 = np.concatenate([data_1, data_3], axis=1)
data_h2

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])