# 134-6 NumPy配列の要素の比較・抽出

## 1問目 NumPy配列とスカラーの比較

In [18]:
import numpy as np

In [19]:
scores = np.array([20 ,62, 78, 45, 85])
scores

array([20, 62, 78, 45, 85])

In [20]:
pass_status = scores >= 60
pass_status

array([False,  True,  True, False,  True])

In [21]:
(scores >= 60) & (scores < 80)

array([False,  True,  True, False, False])

In [22]:
passed_scores = scores[scores >= 60]
passed_scores

array([62, 78, 85])

In [23]:
scores >= 50



array([False,  True,  True, False,  True])

In [24]:
scores[scores >= 80]

array([85])

In [25]:
scores[scores < 60]

array([20, 45])

In [26]:
scores = np.array([20, 63, 78, 45, 85])

In [27]:
scores >= 50

array([False,  True,  True, False,  True])

In [28]:
scores = scores[scores >= 80]

In [29]:
scores

array([85])

In [ ]:
scores = scores[scores < 60]

array([], dtype=int64)

In [31]:
scores

array([], dtype=int64)

In [32]:
import numpy as np

scores = np.array([20, 62, 78, 45, 85])

In [33]:
failed_scores = scores[scores < 60]
failed_scores

array([20, 45])

## STEP1：1人分の点数と合格点を作る

In [34]:
import numpy as np

scores = np.array([20, 62, 78, 45, 85])
passing_scores = np.array([60, 60, 80, 60, 80])

In [35]:
pass_status_1d = scores >= passing_scores
pass_status_1d

array([False,  True, False, False,  True])

In [36]:
scores_2d = np.array([[20, 62, 78, 45, 85],
                      [65, 59, 90, 65, 92]])

In [37]:
scores_2d.shape

(2, 5)

In [39]:
pass_status_2d = scores_2d >= passing_scores
pass_status_2d

array([[False,  True, False, False,  True],
       [ True, False,  True,  True,  True]])

## 10. 演習問題

In [42]:
scores = np.array([70, 55, 82, 40, 90])
passing_scores = np.array([60, 60, 80, 60, 80])

In [43]:
scores >= passing_scores

array([ True, False,  True, False,  True])

In [44]:
scores[scores >= passing_scores]

array([70, 82, 90])

In [46]:
scores_2d = np.array([[70, 55, 82, 40, 90],
                      [50, 65, 79, 70, 81]])
passing_scores = np.array([60, 60, 80, 60, 80])

In [47]:
scores_2d >= passing_scores

array([[ True, False,  True, False,  True],
       [False,  True, False,  True,  True]])

## 「134-6: NumPy配列の要素の比較・抽出」 3問目

In [48]:
import numpy as np

scores = np.array([20, 62, 78, 45, 85])
scores

array([20, 62, 78, 45, 85])

In [49]:
scores >= 60

array([False,  True,  True, False,  True])

In [50]:
pass_count = np.count_nonzero(scores >= 60)

In [51]:
pass_count

3

In [52]:
is_any_passed = np.any(scores >= 60)
is_any_passed

np.True_

In [53]:
is_all_passed = np.all(scores >=  60)
is_all_passed

np.False_

In [54]:
scores = np.array([70, 55, 82, 40, 90])

In [55]:
np.count_nonzero(scores >= 60)

3

In [56]:
np.any(scores >= 60)

np.True_

In [57]:
np.all(scores >= 60)

np.False_

In [59]:
scores2 = np.array([70, 65, 82, 61, 90])

In [60]:
np.count_nonzero(scores2 >= 60)

5

In [64]:
np.any(scores2 >= 60)

np.True_

In [65]:
np.all(scores2 >= 60)

np.True_