# 134-6 NumPy配列の要素の比較・抽出

## 1問目 NumPy配列とスカラーの比較

In [18]:
import numpy as np

In [19]:
scores = np.array([20 ,62, 78, 45, 85])
scores

array([20, 62, 78, 45, 85])

In [20]:
pass_status = scores >= 60
pass_status

array([False,  True,  True, False,  True])

In [21]:
(scores >= 60) & (scores < 80)

array([False,  True,  True, False, False])

In [22]:
passed_scores = scores[scores >= 60]
passed_scores

array([62, 78, 85])

In [23]:
scores >= 50



array([False,  True,  True, False,  True])

In [24]:
scores[scores >= 80]

array([85])

In [25]:
scores[scores < 60]

array([20, 45])

In [26]:
scores = np.array([20, 63, 78, 45, 85])

In [27]:
scores >= 50

array([False,  True,  True, False,  True])

In [28]:
scores = scores[scores >= 80]

In [29]:
scores

array([85])

In [ ]:
scores = scores[scores < 60]

array([], dtype=int64)

In [31]:
scores

array([], dtype=int64)

In [32]:
import numpy as np

scores = np.array([20, 62, 78, 45, 85])

In [33]:
failed_scores = scores[scores < 60]
failed_scores

array([20, 45])