## 「135-2: いろいろなNumPy配列の作成」 1問目

In [1]:
import numpy as np

zero_1d = np.zeros(3)
zero_1d

array([0., 0., 0.])

In [2]:
zero_2d = np.zeros((2, 3))
zero_2d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
one_2d = np.ones((2, 3))
one_2d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
ten_2d = np.full((2, 3), 10)
ten_2d

array([[10, 10, 10],
       [10, 10, 10]])

In [5]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [6]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
c = np.full((2, 4), 7)
c

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [8]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((1, 5))

array([[1., 1., 1., 1., 1.]])

In [10]:
np.full((3, 3), 100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

## 「135-2: いろいろなNumPy配列の作成」 2問目

In [1]:
import numpy as np

In [2]:
data_arange = np.arange(0, 101, 25)
data_arange

array([  0,  25,  50,  75, 100])

In [3]:
np.arange(0, 100, 25)

array([ 0, 25, 50, 75])

In [4]:
data_linspace = np.linspace(0, 100, 5)
data_linspace

array([  0.,  25.,  50.,  75., 100.])

In [5]:
print(data_arange.dtype)

int64


In [6]:
print(data_linspace.dtype)

float64


In [8]:
data_linspace_int = np.linspace(0, 100, 5, dtype="int")
print(data_linspace_int.dtype)
data_linspace_int

int64


array([  0,  25,  50,  75, 100])

In [9]:
a = np.arange(0, 51, 10)
a

array([ 0, 10, 20, 30, 40, 50])

In [11]:
b = np.linspace(0, 1, 5)
b

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
c = np.linspace(0, 100, 6,dtype="int")
c

array([  0,  20,  40,  60,  80, 100])

In [14]:
np.arange(0, 101, 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## 「135-2: いろいろなNumPy配列の作成」 3問目

In [15]:
data_zero = np.zeros(3)
data_zero

array([0., 0., 0.])

In [16]:
data_missing = np.full((3, 4), np.nan)
data_missing

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [17]:
data_25 = np.linspace(-10, 10, 9)
data_25

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ])

In [18]:
a_zero = np.zeros(5)
a_zero

array([0., 0., 0., 0., 0.])

In [19]:
a_missing = np.full((2, 3), np.nan)
a_missing

array([[nan, nan, nan],
       [nan, nan, nan]])

In [20]:
a_line = np.linspace(0, 20, 5)
a_line

array([ 0.,  5., 10., 15., 20.])