## 「135-2: いろいろなNumPy配列の作成」 1問目

In [1]:
import numpy as np

zero_1d = np.zeros(3)
zero_1d

array([0., 0., 0.])

In [2]:
zero_2d = np.zeros((2, 3))
zero_2d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
one_2d = np.ones((2, 3))
one_2d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
ten_2d = np.full((2, 3), 10)
ten_2d

array([[10, 10, 10],
       [10, 10, 10]])

In [5]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [6]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
c = np.full((2, 4), 7)
c

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [8]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((1, 5))

array([[1., 1., 1., 1., 1.]])

In [10]:
np.full((3, 3), 100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

## 「135-2: いろいろなNumPy配列の作成」 2問目