「190-1: NumPyの使い方を学ぼう」 2問目

In [42]:
import numpy as np

In [43]:
# 配列の要素の絶対値を求める
a = [[-3, -2, -1], [0, 1, 2]]
np.abs(a)

array([[3, 2, 1],
       [0, 1, 2]])

In [44]:
b = np.linspace(-1, 1, 10)
b

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [45]:
np.sin(b)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [46]:
c = np.arange(1, 4)
c

array([1, 2, 3])

In [47]:
# 配列cに対してネイピア数を底とする自然対数logを計算する
np.log(c)

array([0.        , 0.69314718, 1.09861229])

In [59]:
x = np.array([[1, 2, 3]])
x
x + 10

array([[11, 12, 13]])

In [60]:
# 配列xと行列yを足す
y = np.array([[10, 20, 30], [40, 50, 60]])
y
y.shape
#x + y

(2, 3)

In [50]:
np.mean(y)
y - np.mean(y)

array([[-25., -15.,  -5.],
       [  5.,  15.,  25.]])

In [51]:
# 配列xのすべての要素を2倍する
x * 2

array([[2, 4, 6]])

In [52]:
# 配列xと行列yを掛ける
x * y

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [53]:
# 配列xを行列yで割る
x / y

array([[0.1  , 0.1  , 0.1  ],
       [0.025, 0.04 , 0.05 ]])

In [54]:
z = np.array([9, 8, 0])
z

array([9, 8, 0])

In [55]:
x / (z + 1e-6)

array([[1.11111099e-01, 2.49999969e-01, 3.00000000e+06]])

In [56]:
# 配列xと行列y1の行列の積
y1 = y.reshape((3, 2))
y1
x @ y1

array([[220, 280]])

In [57]:
# 行列y2と配列xの行列の積
y2 = y.reshape((6, 1))
y2
y2 @ x

array([[ 10,  20,  30],
       [ 20,  40,  60],
       [ 30,  60,  90],
       [ 40,  80, 120],
       [ 50, 100, 150],
       [ 60, 120, 180]])

In [63]:
# 行列yの各要素が15より小さいか判定
y
print(y)
y < 15

[[10 20 30]
 [40 50 60]]


array([[ True, False, False],
       [False, False, False]])

In [65]:
# 配列xと行列yを比較して、要素ごとに等しいかを出力する行列
print(x)
print(y)
x == y
x1 = np.array([1, 2, 3])

[[1 2 3]]
[[10 20 30]
 [40 50 60]]


In [67]:
# 配列xとx1が同じ要素で構成されているか判定
np.allclose(x, x1)
x2 = x + 0.5
x2

array([[1.5, 2.5, 3.5]])

In [ ]:
# 配列xとx2の各要素の誤差が0.3以内か判定
