## 190-1の総復習問題

In [1]:
import numpy as np

In [6]:
x = np.array([[10, -20, 30], [40, 50, -60]])
print("---- x ----")
print(x)
y = np.arange(25, 55, 5).reshape((2, 3))
print("---- y ----")
print(y)
z = np.arange(10, 13, 0.5).reshape((3, 2))
print("---- z ----")
print(z)

---- x ----
[[ 10 -20  30]
 [ 40  50 -60]]
---- y ----
[[25 30 35]
 [40 45 50]]
---- z ----
[[10.  10.5]
 [11.  11.5]
 [12.  12.5]]


In [8]:
# 行列xの要素の絶対値
x_abs = np.abs(x)
x_abs

array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
# 行列yの要素の自然対数をとる
y_log = np.log(y)
y_log

array([[3.21887582, 3.40119738, 3.55534806],
       [3.68887945, 3.80666249, 3.91202301]])

In [12]:
# 行列xのすべての要素に5を足す
x1 = x + 5
print(x)
x1

[[ 10 -20  30]
 [ 40  50 -60]]


array([[ 15, -15,  35],
       [ 45,  55, -55]])

In [13]:
# 行列xと行列yの和
print(x)
print(y)
xy = x + y
xy

[[ 10 -20  30]
 [ 40  50 -60]]
[[25 30 35]
 [40 45 50]]


array([[ 35,  10,  65],
       [ 80,  95, -10]])

In [14]:
# 行列xと行列zの行列の積
prod_xz = np.dot(x, z)
print(x)
print(z)
prod_xz

[[ 10 -20  30]
 [ 40  50 -60]]
[[10.  10.5]
 [11.  11.5]
 [12.  12.5]]


array([[240., 250.],
       [230., 245.]])

In [16]:
# 行列zと行列xの行列の積
prod_zx = np.dot(z, x)
print(z)
print(x)
prod_zx

[[10.  10.5]
 [11.  11.5]
 [12.  12.5]]
[[ 10 -20  30]
 [ 40  50 -60]]


array([[ 520.,  325., -330.],
       [ 570.,  355., -360.],
       [ 620.,  385., -390.]])

In [18]:
# 行列xと行列yを比較して、要素ごとに等しいかを出力する行列
copy_xy = x == y
print(x)
print(y)
copy_xy

[[ 10 -20  30]
 [ 40  50 -60]]
[[25 30 35]
 [40 45 50]]


array([[False, False, False],
       [ True, False, False]])