## 190-1: NumPyの使い方を学ぼう 1問目

In [2]:
import numpy as np

In [3]:
# 1次元配列を作ります
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
# 2次元配列を作ります
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 配列aの2〜3番目の要素
a[1:]

array([2, 3])

In [6]:
# 行列bの1、2行目、2〜3番目の要素
b[:, 1:]

array([[2, 3],
       [5, 6]])

In [7]:
# 行列bの1行目、2〜3番目の要素
b[:1, 1:]

array([[2, 3]])

In [9]:
# 0から9までの数列
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 1から10までの数列
d = np.arange(1, 11)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# 引数が3つあるとき、3番目の引数は数同士の間隔になります
c2 = np.arange(1, 11, 2)
c2

array([1, 3, 5, 7, 9])

In [13]:
x = np.array([10, 20, 30, 40])
y = np.array([50, 60, 70, 80])

In [14]:
# 配列x, yを水平方向に結合
xy_h = np.hstack([x, y])
xy_h

array([10, 20, 30, 40, 50, 60, 70, 80])

In [15]:
# 配列x, yを垂直方向に結合
xy_v = np.vstack([x, y])
xy_v

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [17]:
# 指定された範囲で均等割りした配列
z = np.linspace(0, 1, 5)
z

array([0.  , 0.25, 0.5 , 0.75, 1.  ])