##　実務演習問題　完成版

In [2]:
import numpy as np

In [9]:
defects = np.array([12, 18, 9, 25, 21, 10])
defects

array([12, 18,  9, 25, 21, 10])

In [8]:
production = np.array([1000, 1200, 1200, 1300, 1250, 1150])
production

array([1000, 1200, 1200, 1300, 1250, 1150])

In [7]:
months = np.arange(1, 7)
months

array([1, 2, 3, 4, 5, 6])

In [11]:
first_half_defects = defects[:3]
first_half_defects

array([12, 18,  9])

In [13]:
second_half_defects = defects[3:]
second_half_defects

array([25, 21, 10])

In [15]:
quality_table = np.vstack([defects, production])
quality_table

array([[  12,   18,    9,   25,   21,   10],
       [1000, 1200, 1200, 1300, 1250, 1150]])

In [17]:
check_line = np.linspace(0, 1, 5)
check_line

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
mdstack = np.vstack([months, defects])
mdstack

array([[ 1,  2,  3,  4,  5,  6],
       [12, 18,  9, 25, 21, 10]])

In [18]:
monster_months = months[defects >= 20]
monster_months

array([4, 5])

In [21]:
monster_defects = defects[defects >=20]
monster_defects

array([25, 21])