## 135-3: NumPyで乱数を作ろう

In [2]:
import numpy as np

In [3]:
rng = np.random.default_rng()

In [4]:
rnd1 = rng.random(10)

In [5]:
rnd1

array([0.96918828, 0.4583162 , 0.99023363, 0.86345669, 0.14028979,
       0.60136802, 0.21510019, 0.69239569, 0.96591481, 0.59641994])

In [6]:
rnd2 = rng.random((2, 5))

In [7]:
rnd2

array([[0.13015604, 0.01224054, 0.37581214, 0.2224207 , 0.60574245],
       [0.47053909, 0.07615925, 0.53177253, 0.52671549, 0.03253423]])

In [8]:
rng.random()

0.029830732533360105

In [9]:
rng.random(10)

array([0.78787439, 0.73572321, 0.34076559, 0.60180296, 0.73897004,
       0.82828152, 0.54256125, 0.07822431, 0.20252105, 0.14434903])

In [10]:
rng.random((2, 5))

array([[0.62170611, 0.49688353, 0.83996525, 0.16251131, 0.02026911],
       [0.01780264, 0.97130427, 0.61939841, 0.82229905, 0.1057075 ]])

In [11]:
rnd3 = rng.uniform(3, 8, 10)
rnd3

array([5.04830056, 7.14973941, 4.95782482, 5.08993471, 7.97753168,
       3.83852896, 7.78534225, 3.7901578 , 3.65305309, 6.19936268])

In [12]:
rnd4 = rng.uniform(3, 8, (2, 5))
rnd4

array([[7.4554366 , 7.770471  , 5.37906981, 5.65988666, 7.64917507],
       [4.16169469, 5.26559834, 4.98406245, 4.12815699, 5.07298364]])

In [13]:
rnd5 = rng.integers(3, 8, 10)
rnd5

array([7, 7, 4, 5, 5, 6, 7, 5, 5, 6])

In [14]:
rng.random(10)

array([0.67714223, 0.56001154, 0.6395525 , 0.22733974, 0.53120674,
       0.37040968, 0.39007661, 0.09471726, 0.09592915, 0.36640928])

In [15]:
rng.uniform(3, 8, 10)

array([7.39315318, 4.7898622 , 5.20194201, 4.66966645, 7.52027946,
       6.20779261, 7.05648162, 5.68196751, 4.71325575, 7.01557552])

In [16]:
rng.integers(3, 8, 10)

array([6, 3, 4, 4, 5, 3, 5, 4, 6, 7])

In [18]:
practice1 = rng.random(10)
practice1

array([0.96594693, 0.23867998, 0.44809786, 0.69414427, 0.65968057,
       0.53215174, 0.72576577, 0.57070273, 0.64737663, 0.93184   ])

In [20]:
practice1 = rng.random(5)
practice1

array([0.80309819, 0.65627357, 0.99839242, 0.23858197, 0.66198433])

In [21]:
practice2 = rng.uniform(10, 20, 6)
practice2

array([12.84158321, 11.86337395, 14.00946983, 17.80086568, 10.14526075,
       18.81725093])

In [22]:
practice3 = rng.integers(1, 7, 10)
practice3

array([1, 6, 4, 3, 2, 4, 6, 4, 1, 3])

In [23]:
practice4 = rng.random((3, 4))

In [24]:
practice4

array([[0.35611632, 0.70338474, 0.88484402, 0.12199466],
       [0.68632932, 0.45576391, 0.33852202, 0.54099323],
       [0.74308583, 0.57294249, 0.96565808, 0.72495601]])

In [26]:
change1 = rng.uniform(5, 10, (2, 3))
change1

array([[5.37103537, 7.18900459, 5.37191176],
       [5.69174575, 5.65648738, 6.74394032]])

In [28]:
change2 = rng.integers(100, 200, 5)
change2

array([188, 145, 196, 188, 119])

In [29]:
change3 = rng.random()
change3

0.6142647001688724

## 「135-3: NumPyで乱数を作ろう」 2問目

In [30]:
import numpy as np

In [31]:
rng = np.random.default_rng()

In [32]:
targets = ["A", "B", "C"]

In [35]:
rnd1 = rng.choice(targets, 4)
rnd1

array(['B', 'B', 'B', 'B'], dtype='<U1')

In [38]:
rnd2 = rng.choice(targets, (2, 3))
rnd2

array([['A', 'B', 'C'],
       ['C', 'C', 'A']], dtype='<U1')

In [40]:
rng.choice(targets)

np.str_('C')

In [44]:
rnd3 = rng.choice(targets, 3, replace=False)
rnd3

array(['A', 'B', 'C'], dtype='<U1')

In [46]:
rnd4 = rng.permutation(targets)
rnd4

array(['B', 'C', 'A'], dtype='<U1')

In [47]:
targets

['A', 'B', 'C']

In [50]:
rng.shuffle(targets)

In [51]:
targets

['A', 'C', 'B']

## 135-3: NumPyで乱数を作ろう

In [52]:
import numpy as np

In [53]:
rng = np.random.default_rng()

In [54]:
rnd1 = rng.normal(50, 10, 10)
rnd1

array([58.31275566, 50.72223582, 34.47925787, 37.98946799, 46.01018635,
       41.59179429, 64.52398028, 53.70119323, 52.54214745, 57.6482118 ])

In [55]:
rnd2 = rng.normal(50, 10, (2, 5))
rnd2

array([[31.46509508, 50.82915958, 56.47736811, 40.28732856, 37.16441007],
       [33.26306735, 25.19093611, 62.46093863, 40.58603696, 51.47292019]])

In [56]:
rnd3 = rng.standard_normal(10)
rnd3

array([-0.44148057,  0.02836752, -0.80629994,  0.92626404,  0.20625627,
       -2.18893562, -0.04606191, -1.13169381,  0.77799903,  1.36740233])

In [57]:
rnd4 = rng.binomial(20, 0.4, 10)
rnd4

array([ 8, 10,  7,  6,  8,  7,  6,  7,  7,  8])

In [58]:
rnd5 = rng.poisson(9.8, 10)
rnd5

array([10, 10,  5, 15, 11, 12, 11,  5,  8,  7])

In [59]:
rnd6 = rng.beta(1, 2, 10)
rnd6

array([0.44487865, 0.12429598, 0.09977658, 0.40529808, 0.51258442,
       0.0496541 , 0.61022256, 0.5639559 , 0.43419744, 0.05120972])

In [60]:
rnd7 = rng.multivariate_normal([0, 0], [[1, 0.5], [0.5, 1]])
rnd7

array([-0.9223579 , -0.63363923])

## 問題1

平均60、標準偏差5の正規分布にしたがう乱数を、  
2行3列で作り、変数 `change1` に入れてください。

In [61]:
change1 = rng.normal(60, 5, (2, 3))
change1

array([[64.92708776, 63.65029015, 63.12936572],
       [74.43772652, 59.76616502, 55.41160984]])

## 問題2

成功確率50%の試行を100回行ったときの成功回数を、10個作り、変数 change2 に入れてください。

In [62]:
change2 = rng.binomial(100, 0.5, 10)
change2

array([47, 56, 53, 55, 49, 49, 48, 53, 48, 50])

## 問題3

平均12回発生する出来事について、7個の発生回数を作り、変数 change3 に入れてください。

In [63]:
change3 = rng.poisson(12, 7)
change3

array([15, 12, 15, 11, 11, 10, 10])