In [1]:
import numpy as np

In [2]:
prices = np.array([100 ,130 ,180])
prices

array([100, 130, 180])

In [3]:
type(prices)

numpy.ndarray

In [4]:
prices[0]

np.int64(100)

In [5]:
prices[1]

np.int64(130)

In [6]:
prices[2]

np.int64(180)

In [7]:
prices_with_tax = prices * 1.08
prices_with_tax

array([108. , 140.4, 194.4])

In [8]:
discounted_prices = prices - 10
discounted_prices

array([ 90, 120, 170])

In [9]:
import numpy as np

prices2 = np.array([200, 250, 300])
prices2_with_tax = prices2 * 1.08
prices2_with_tax

array([216., 270., 324.])

In [11]:
import numpy as np

prices3 = np.array([500, 700, 900])
discounted_prices3 = prices3 - 0.95

discounted_prices3

array([499.05, 699.05, 899.05])

In [12]:
import numpy as np

prices4 = np.array([80, 120, 160])
new_prices4 = prices4 * 20

new_prices4

array([1600, 2400, 3200])