In [2]:
import numpy as np

In [3]:
prices = np.array([100, 130, 180])
prices

array([100, 130, 180])

In [4]:
quantities = np.array([20, 10, 5])
quantities

array([20, 10,  5])

In [5]:
amounts = np.dot(prices, quantities)
amounts

np.int64(4200)

In [6]:
amounts = prices * quantities
amounts

array([2000, 1300,  900])

In [7]:
import numpy as np

prices2 = np.array([200, 300, 400])
quantities2 = np.array([2, 3, 4])

amounts2 = np.dot(prices2, quantities2)
amounts2

np.int64(2900)

In [8]:
import numpy as np

prices3 = np.array([50, 60, 70])
quantities3 = np.array([1, 2, 3])

amounts3 = np.dot(prices3, quantities3)
amounts3

np.int64(380)

In [10]:
import numpy as np

prices4 = np.array([1000, 2000, 3000])
quantities4 = np.array([1, 1, 2])

amounts4 = prices4 @ quantities4
amounts4

np.int64(9000)