In [1]:
import numpy as np

In [2]:
prices = np.array([100, 130, 180])
prices

array([100, 130, 180])

In [3]:
discounts = np.array([10, 20, 25])
discounts

array([10, 20, 25])

In [4]:
quantities = np.array([20, 10, 5])
quantities

array([20, 10,  5])

In [6]:
discounted_prices = prices - discounts
discounted_prices

array([ 90, 110, 155])

In [7]:
amounts = discounted_prices * quantities
amounts

array([1800, 1100,  775])

In [11]:
import numpy as np
prices2 = np.array([200, 250, 300])
discounts2 = np.array([20, 30, 50])
quantities2 = np.array([3, 4, 5])

discounted_prices2 = prices2 - discounts2
amounts2 = discounted_prices2 * quantities2

discounted_prices2
amounts2

array([ 540,  880, 1250])

In [12]:
import numpy as np
prices3 = np.array([500, 700, 900])
discounts3 = np.array([50, 100, 150])
discounts_prices3 = prices3 - discounts3
discounts_prices3

array([450, 600, 750])

In [14]:
import numpy as np

discounted_prices4 = np.array([80, 120, 150])
quantities4 = np.array([2, 3, 4])

amounts4 = discounted_prices4 * quantities4
amounts4

array([160, 360, 600])