## # 136-2 NumPy配列の転置

In [1]:
import numpy as np

In [2]:
rainfalls_all = np.array(
    [
        [120, 130, 140, 110, 90, 100, 115, 135, 145, 110, 105, 125],  # 都市A
        [115, 140, 135, 120, 95, 105, 110, 120, 150, 115, 110, 130],  # 都市B
        [130, 125, 140, 115, 100, 90, 120, 125, 155, 130, 115, 140],  # 都市C
    ]
)

In [3]:
rainfalls_all.shape

(3, 12)

In [4]:
rainfalls_t = rainfalls_all.T

In [5]:
rainfalls_t

array([[120, 115, 130],
       [130, 140, 125],
       [140, 135, 140],
       [110, 120, 115],
       [ 90,  95, 100],
       [100, 105,  90],
       [115, 110, 120],
       [135, 120, 125],
       [145, 150, 155],
       [110, 115, 130],
       [105, 110, 115],
       [125, 130, 140]])

In [6]:
import numpy as np

data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

data_t = data.T
data_t

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
import numpy as np

scores = np.array([
    [80, 90, 70, 85],
    [75, 88, 92, 81],
    [60, 72, 78, 90]
])

scores.shape

(3, 4)

In [8]:
scores_t = scores.T

In [9]:
scores_t

array([[80, 75, 60],
       [90, 88, 72],
       [70, 92, 78],
       [85, 81, 90]])

## 「136-2: NumPy配列の転置」 2問目

In [10]:
import numpy as np

In [11]:
data = np.array(
    [
        [28, 30, 29, 31, 32, 33, 30],  # 最高気温（°C）
        [18, 19, 20, 21, 22, 20, 19],  # 最低気温（°C）
        [50, 55, 53, 58, 60, 65, 59],  # 売上（万円）
    ]
)

In [13]:
data.shape

(3, 7)

In [14]:
after_data = data.T

In [15]:
after_data

array([[28, 18, 50],
       [30, 19, 55],
       [29, 20, 53],
       [31, 21, 58],
       [32, 22, 60],
       [33, 20, 65],
       [30, 19, 59]])

In [16]:
after_data.shape

(7, 3)

In [17]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [1, 2, 3]
])

after_data = data.T

In [18]:
after_data.shape

(3, 2)

In [19]:
after_data

array([[10,  1],
       [20,  2],
       [30,  3]])